### ISSUE TITLE
Incompatibility with BYG

### ISSUE THREAD

**Issue by Inpaladin** [CorgiTaco-Archive/Upstream#2]
Title.  Rivers will flow normally through vanilla biomes but will be cut off by any biomes added by BYG.
![image](https://user-images.githubusercontent.com/59532097/102846973-45e2a900-43c6-11eb-82ba-d0311bb93afb.png)
screenshot of a worldmap

**Comment by CorgiTaco** [comment]
Delete the config where biomes are listed and let it regenerate

**Comment by Inpaladin** [comment]
I was just about to close this issue since I realized I hadn't checked if I'd actually registered any of the byg biomes lmao, thanks for responding anyways though.  Sorry to bother.
